# Configurations of ${applicationName}.

# Default theme for this app.
theme : "org.wso2.carbon.uuf.common.default.theme"

# Menus in this app.
menus :
  - name: "main"
    items:
      - text: "Home"
        link: "#"
        icon: "fw-home"
        submenus:
          - text: "Items"
            link: ""

# Error pages for this app.
errorPages:
  404: "/foundation/error/404"
  default: "/foundation/error/default"

# URI of the login page in this app.
loginPageUri: "/simple-auth/login"

# Security related configurations for this app.
security:
  csrfPatterns:
    accept: []
    reject: []
  xssPatterns:
    accept: []
    reject: []
  responseHeaders:
    "X-Frame-Options": "DENY"
